[module]
name = "current-workspace"
version = 1
description = "Displays the active workspace. This can later become the workspace overview button."
style = "style.css"

[generator]
entrypoint = "scripts/generate.py"

[dependencies]
commands = ["hyprctl", "python3"]

[dependencies.arch]
packages = ["hyprland", "python"]
